# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pim_qLDLc-wY8TalDGecp4LXQAYfh0zO
"""



"""1)"""

def sum_three(x,y,z) :
 if  x == y or y == z or z == x :
    sum = 3
 else:
    sum = 0
 return sum
 print(sum_three(5 , 5, 5))
 print(sum_three(3 ,4 , 1))

"""2)"""

def DtoLoT(dict) :
  dict = { 'BHAKTI' : 38 , 'PRABHU' : 42}
  list = [(k,v) for k,v in dict.items()]
  list.sort(key = lambda x: x[0])
  return list
  print(DtoLoT(dict))
  [('BHAKTI',38), ('PRABHU',42)]

"""3)"""

def function2(list) :
  list = ["m","n","p","r","c"]
  b= dict((i, i.upper()) for i in list)
  return b
  print(function2(list))

"""4)"""

def replaceVowel(str , K) :
  vowels = 'aeiou'
  for i in vowels :
      str = str.replace(i,K)
      return str
input_str = " Python is computer language "
k = "b"
print("input string =" , input_str)
print("specified vowel =", K)
print("after replacing =" , replaceVowels(input_str,K))

Input string =" Python is computer language "
Specified vowel = e
After replacing = " Python is computer language"

"""5)"""

def Python (sy) :
  ab = []
  for index, c in enumerate(sy) :
    if index % 2 == 0:
      ab.append(c.upper())
    else:
      ab.append(c.lower())
    return''.join(ab)
    print(Python("Python is computer language:"))

"""6)"""

def fact(n):
  fact = 1
  for i in range(1 ,n+1) :
    fact= fact*i
    print(fact)
    fact(5)

"""7)"""

def rotate(a,d) :
  n = len(a)
  a[:] =a[d:n]+a[0:d]
  return a
  a = [3,4,5,6,8,9,1]
  print("Rotated list is")
  print(rotate(a,1))

"""8)"""

colors = {}
def insert (a) :
  if a in colors:
    colors[a]+=1
  else :
      colors[a] = 1
      insert('Red')
      insert('green')
      insert('Blue')
      insert('White')
      insert('Red')
      print(len(colors))

"""9)"""

def sumlist(list) :
  sum=0
  for i in range(len(list)) :
    sum = sum+list[i]
    return sum
    list =[20,40,60]
    print(list)
    print("sum of list:",sumlist(list))

"""10)"""

def mul_list(list):
  product = 1
  for i in list:
    product = product *i 
    return product
    list1 = [5,6,7,8]
    print(list1)
    print("product:")
    print(mul_list(list1))